// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAurwSEusplOtWn6RHVlCUYD9Ssl8nv6vQ',
    appId: '1:300767404611:web:252293f9d4d06672716af6',
    messagingSenderId: '300767404611',
    projectId: 'placed-ac030',
    authDomain: 'placed-ac030.firebaseapp.com',
    storageBucket: 'placed-ac030.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJuxbb4fQ6t7ocDzkMqFOch__FSRGweM',
    appId: '1:300767404611:android:3bdf792e35d5823c716af6',
    messagingSenderId: '300767404611',
    projectId: 'placed-ac030',
    storageBucket: 'placed-ac030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYtUzRZqz7DkrcUwUe1-vyLVcL6iapewM',
    appId: '1:300767404611:ios:d32846b5a922e4b4716af6',
    messagingSenderId: '300767404611',
    projectId: 'placed-ac030',
    storageBucket: 'placed-ac030.appspot.com',
    iosBundleId: 'com.example.placedMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYtUzRZqz7DkrcUwUe1-vyLVcL6iapewM',
    appId: '1:300767404611:ios:71afa38115bcf185716af6',
    messagingSenderId: '300767404611',
    projectId: 'placed-ac030',
    storageBucket: 'placed-ac030.appspot.com',
    iosBundleId: 'com.example.placedMobileApp.RunnerTests',
  );
}
